In [75]:
import numpy as np

# Aufgabe 2: QR Zerlegung

In [76]:
# QR - Zerlegung
def qr_decomp(A):
    n = A.shape[0]
    Q = np.zeros(shape=A.shape)
    for index in range(n):
        a = A[:,index].copy()
        u = a 
    
        for j in range(index):
            u -= (Q[:,j].dot(a)) * Q[:,j]
        
        # Q entsprechend berechnen
        Q[:,index] = u / np.linalg.norm(u)
    R = Q.T.dot(A)
    return Q,R

# Eigenwerte
def qr_algorithm(A):
    S = qr_decomp(A)[0].copy()
    I = np.identity(A.shape[0])
    A_1 = qr_decomp(A)[1].dot(qr_decomp(A)[0])

    for i in range(2000):
        Q, R = qr_decomp(A_1)
        A_1 = R.dot(Q)
        S = S.dot(Q)
    
    eigenvalues = ()
    for diag in range(A.shape[0]):
        eigenvalues = eigenvalues + (A_1[diag][diag],)
        
    return eigenvalues,S
        
A = np.asarray(((1, 4, 8, 4), (4, 2, 3, 7), (8, 3, 6, 9), (4, 7, 9, 2)), dtype="float64")
print("Own Solution: ", qr_algorithm(A)[0])
print("Numpy Solution: ", np.linalg.eig(A)[0])
print("Own Solution: \n",qr_algorithm(A)[1])
print("Numpy Solution: \n", np.linalg.eig(A)[1])


Own Solution:  (21.0, -8.000000000000002, -2.9999999999999996, 1.0000000000000016)
Numpy Solution:  [21. -8. -3.  1.]
Own Solution: 
 [[ 0.43151697  0.38357064  0.77459667 -0.25819889]
 [ 0.38357064 -0.43151697  0.25819889  0.77459667]
 [ 0.62330229 -0.52740963 -0.25819889 -0.51639778]
 [ 0.52740963  0.62330229 -0.51639778  0.25819889]]
Numpy Solution: 
 [[ 0.43151697  0.38357064 -0.77459667  0.25819889]
 [ 0.38357064 -0.43151697 -0.25819889 -0.77459667]
 [ 0.62330229 -0.52740963  0.25819889  0.51639778]
 [ 0.52740963  0.62330229  0.51639778 -0.25819889]]
